### ISSUE TITLE
run on each rebuild

### ISSUE THREAD

**Issue by shime** [arschmitz/ember-cli-standard#2]
It would be nice to run standard on each rebuild, like how jshint is ran.

**Comment by arschmitz** [comment]
This already does that. It works exactly as jshint does.

**Comment by shime** [comment]
Hm, it doesn't for me.

``` bash
$ ember -v
ember-cli: 2.7.0
node: 6.7.0
os: darwin x64
$ grep ember bower.json | head -n 1
    "ember": "~2.7.0",
```

**Comment by arschmitz** [comment]
closing this it runs exactly liek the default eslint and is actually essentially a fork of that
